[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = "Bookstore API"
authors = ["deep_writer"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.4.2"
factory-boy = "^3.3.3"
Django = "^5.2.7"
django-rest-framework = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
